\paragraph{Вывод:}
\begin{sloppypar}
    Я создал иерархию исключений наследуясь от базового класса \texttt{std::exceptions}.
    Также создал ситуацию создания исключений и успешно словил их в блоке \texttt{try...catch}.
    Если блок \texttt{try...catch} ловит родительское исключение, то он автоматически ловит и дочернее.
    Также важна последовательность блоков \texttt{catch}, так как они срабатывают в том порядке, в каком написаны в коде программы.
\end{sloppypar}
